services:
  - type: web
    name: backend-portfolio
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && ./start.sh"
    envVars:
      - key: FLASK_APP
        value: run.py
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: demoresto-data
          property: connectionString

databases:
  - name: demoresto-data