"""Change password_hash to Text

Revision ID: 360a436a9b45
Revises: 6b19f1c4ddec
Create Date: 2025-05-21 12:04:49.092348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360a436a9b45'
down_revision = '6b19f1c4ddec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
