"""Modif bug commande

Revision ID: 07482c5636a3
Revises: da60fdf9b3f1
Create Date: 2025-05-30 12:59:21.467635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07482c5636a3'
down_revision = 'da60fdf9b3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_order_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
