"""Ajout de nouveaux champs/classes

Revision ID: 1dcdb6715a00
Revises: e46e4d298ebf
Create Date: 2025-06-02 19:57:47.769315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcdb6715a00'
down_revision = 'e46e4d298ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
