"""Ajout des champs dans Reservation et User

Revision ID: 30505095fa14
Revises: 74946340383f
Create Date: 2025-05-22 22:56:07.461528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30505095fa14'
down_revision = '74946340383f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('couverts', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('heure', sa.String(length=20), nullable=False),
    sa.Column('commentaire', sa.Text(), nullable=True),
    sa.Column('commentaire_admin', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
