"""Ajout de nouveaux champs/classes

Revision ID: 459399453970
Revises: 30505095fa14
Create Date: 2025-05-28 12:12:39.254251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459399453970'
down_revision = '30505095fa14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
