"""Allergies

Revision ID: 5f4973039dee
Revises: 9f98ac7e48db
Create Date: 2025-05-30 22:07:29.104722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4973039dee'
down_revision = '9f98ac7e48db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergenes_exclus', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('allergenes_exclus')

    # ### end Alembic commands ###
