"""Ajout de nouveaux champs/classes

Revision ID: 74946340383f
Revises: e8fc3ba15a9a
Create Date: 2025-05-21 19:54:35.729564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74946340383f'
down_revision = 'e8fc3ba15a9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
