"""Modif livraison

Revision ID: 817015d293a6
Revises: 07482c5636a3
Create Date: 2025-05-30 15:58:50.160470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817015d293a6'
down_revision = '07482c5636a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pickup_info', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('pickup_info')
        batch_op.drop_column('delivery_info')

    # ### end Alembic commands ###
