"""Heure et date de commande résumé user

Revision ID: 9f98ac7e48db
Revises: cf8e8d095d16
Create Date: 2025-05-30 20:05:21.470832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f98ac7e48db'
down_revision = 'cf8e8d095d16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_date', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('requested_time', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('requested_time')
        batch_op.drop_column('requested_date')

    # ### end Alembic commands ###
