"""trend produits enlver

Revision ID: af91e815ad1b
Revises: 4d2e67f94db1
Create Date: 2025-06-03 21:56:57.961418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af91e815ad1b'
down_revision = '4d2e67f94db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('is_trending')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_trending', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
