"""Modif livraison

Revision ID: cf8e8d095d16
Revises: 817015d293a6
Create Date: 2025-05-30 16:14:19.137188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8e8d095d16'
down_revision = '817015d293a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('pickup_info')
        batch_op.drop_column('delivery_info')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_info', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pickup_info', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
